apiVersion: apps/v1
kind: Deployment #what i want to create
metadata:
  name: influxdb #name of deployment
spec: #specification for deplyment
  selector:
    matchLabels:
      app: influxdb
  replicas: 1 #how many replicas i want
  template:
    metadata:
      labels:
        app: influxdb
    spec: #specficiation for pod
      containers:
      - name: influxdb #we want one container inside of the pod
        image: my_influxdb #the image
        imagePullPolicy: Never #pas aller chercher dans docker hub
        ports:
        - containerPort: 8086
          name: influxdbport
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "service influxdb status"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
