apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
   metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: mysql
  ports:
  - name: mysqlport
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
