apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    orgId: 1
    uid: my_unique_uid
    url: http://localhost:8086
    password: password
    user: telegrafuser
    database: telegraf
