apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
   metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  ports:
  - name: wordpressport
    protocol: TCP
    port: 5050
    targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
