apiVersion: apps/v1
kind: Deployment #what i want to create
metadata:
  name: mysql-deployment #name of deployment
spec: #specification for deplyment
  selector:
    matchLabels:
      app: mysql
  replicas: 1 #how many replicas i want
  template:
    metadata:
      labels:
        app: mysql
    spec: #specficiation for pod
      containers:
      - name: mysql #we want one container inside of the pod
        image: my_mysql #the image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysqlport
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
