apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
   metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: influxdb
  ports:
  - name: influxdbport
    protocol: TCP
    port: 8086
    targetPort: 8086
  type: ClusterIP
